### ISSUE TITLE
Exception while trying to store an array of contracts in Solidity

### ISSUE THREAD

**Issue by VoR0220** [hyperledger/burrow#413]
This was reported by a user who used some interesting code. It compiles in browser solidity and runs properly but doesn't on our stack. Here's the report of what I did to reproduce:

Solidity code:

```
contract House {
  Person[] persons;
 
  function addPerson(address personAddress) {
    persons.push(Person(personAddress));
  }
 
  function getPersonByIndex(uint index) constant returns(address personAddres, string name, uint age) {
    Person p = persons[index];
 
    personAddres = address(p);
    name = bytes32ToString(p.getNameBytes());
    age = p.getAge();
 
    return (personAddres, name, age);
  }
  // stolen from: http://ethereum.stackexchange.com/questions/2519/how-to-convert-a-bytes32-to-string
  function bytes32ToString(bytes32 x) constant returns (string) {
    bytes memory bytesString = new bytes(32);
    uint charCount = 0;
    for (uint j = 0; j < 32; j++) {
        byte char = byte(bytes32(uint(x) * 2 ** (8 * j)));
        if (char != 0) {
            bytesString[charCount] = char;
            charCount++;
        }
    }
 
    bytes memory bytesStringTrimmed = new bytes(charCount);
    for (j = 0; j < charCount; j++) {
        bytesStringTrimmed[j] = bytesString[j];
    }
    return string(bytesStringTrimmed);
  }
}
 
contract Person {
  string _name;
  uint _age;
 
  function Person(string name, uint age) {
    _name = name;
    _age = age;
  }
 
  function getName() constant returns (string) {
    return _name;
  }
 
  function getAge() constant returns (uint) {
    return _age;
  }
 
  function getNameBytes() constant returns (bytes32) {
    return stringToBytes32(_name);
  }
  // stolen from: http://ethereum.stackexchange.com/questions/9142/how-to-convert-a-string-to-bytes32
  function stringToBytes32(string memory source) returns (bytes32 result) {
    assembly {
        result := mload(add(source, 32))
    }
  }
}
```

EPM.Yaml:

```
jobs:

- name: deployPerson
  job:
    deploy:
      contract: houseAndPerson.sol
      instance: Person
      data:
        - "hello"
        - 12
      wait: true

- name: deployHouse
  job:
    deploy:
      contract: houseAndPerson.sol
      instance: House
      wait: true

- name: insertPerson
  job:
    call:
      destination: $deployHouse
      function: addPerson
      data:
        - $deployPerson
      wait: true

- name: getPerson
  job:
    call:
      destination: $deployHouse
      function: getPersonByIndex
      data:
        - 0
      wait: true

- name: assertPerson
  job:
    assert:
      key: $getPerson.name
      relation: eq
      val: "hello"
```

and finally the output:

```
Deploying Contract                       name=House
                                         addr=B7427F27B4E7A444C9765280F2954960BDB5CFBC
Executing Job                                 insertPerson
Executing Job                                 getPerson
Encountered Exception from chain w: %!s(<nil>)

Executing Job                                 assertPerson
Assertion Failed                              $getPerson.name == hello
assertion failed

Could not perform pkg action service: Could not perform pkg action: Container interactive-3ce29cea-ce94-403a-9164-4e5695251a2a exited with status 1
```
