### ISSUE TITLE
Solidity file with an abstract function is undeployable

### ISSUE THREAD

**Issue by Luker501** [hyperledger/burrow#846]
- `burrow version`: 0.20.1+commit.v0.18.0-186-g92dad94
- `go version`: 1.10.3 linux/amd64
- operating system details (osx/windows/linux): Ubuntu 16.04.4 LTS
- what you expected to happen: A solidity smart contract with an abstract function to be deployable
- what actually happened:  The smart contract was not deployable
- steps to reproduction:

Following [this tutorial](https://github.com/monax/bosmarmot) the burrow chain is on, contract storage.sol has been deployed and the tests in the epm.yaml file have passed.

Next I created a basic solidity file with an abstract function in named AbstractContract.sol:

```
pragma solidity ^0.4.20;

contract AbstractContract {

  function getBool() public returns (bool retBool);

}
```

This contract has no compile errors according to remix.ethereum.org. But it does not deploy to the chain. I added the following in my epm.yaml file to check:

```
- name: deployAbstractContract
  deploy:
    contract: AbstractContract.sol

- name: makeSureDeployed1
  assert:
    key: $deployAbstractContract
    relation: ne
    val: ""
```

The above fails. But if I change the AbstractContract to the following, the above will succeed:

```
pragma solidity ^0.4.20;

contract AbstractContract {

  function getBool() public returns (bool retBool){
	return true;
  }

}
```
