### ISSUE TITLE
Cannot reset an int/uint to zero

### ISSUE THREAD

**Issue by Luker501** [hyperledger/burrow#847]
Please include in your bug report:

- `burrow version`: 0.20.1+commit.v0.18.0-186-g92dad94
- `go version`: 1.10.3 linux/amd64
- operating system details: Ubuntu 16.04.4 LTS
- what you expected to happen: to be able to reset a uint or an int to zero 
- what actually happened: I cannot get this to work via yaml or solidity.
- steps to reproduction:

I've modified the storage.sol and epm.yaml from [this tutorial](https://github.com/monax/bosmarmot) to show the issue. 

Firstly see the storageIssueWithZero.sol below. Note that I have added two functions (setIntToZero and setUintToZero) to set the int/uint to zero within the code:

```
pragma solidity ^0.4.20;

contract storageIssueWithZero {

  int private storedInt;
  uint private storedUint;

  function setInt(int x) public {
    storedInt = x;
  }

  function setIntToZero() public {
    storedInt = 0;
  }

  function getInt() constant public returns (int retInt) {
    return storedInt;
  }

  function setUint(uint x) public {
    storedUint = x;
  }

  function setUintToZero() public {
    storedUint = 0;
  }

  function getUint() constant public returns (uint retUint) {
    return storedUint;
  }

}
```

Now my yaml test file is as follows:

```
jobs:

- name: deployStorageK
  deploy:
    contract: storageIssueWithZero.sol

- name: makeSureDeployed
  assert:
    key: $deployStorageK
    relation: ne
    val: ""

#set Int to 5000
- name: setStorageBaseInt
  set:
    val: 50000

- name: setStorageInt
  call:
    destination: $deployStorageK
    function: setInt
    data: [$setStorageBaseInt]

- name: queryStorageInt
  query-contract:
    destination: $deployStorageK
    function: getInt

- name: assertStorageInt
  assert:
    key: $queryStorageInt
    relation: eq
    val: $setStorageBaseInt

#set Int to Zero using Yaml
- name: setStorageBaseInt2
  set:
    val: 0

- name: setStorageInt2
  call:
    destination: $deployStorageK
    function: setInt
    data: [$setStorageBaseInt2]

- name: queryStorageInt2
  query-contract:
    destination: $deployStorageK
    function: getInt

- name: assertStorageInt2
  assert:
    key: $queryStorageInt2
    relation: ne
    val: $setStorageBaseInt2

#set Int to Zero using solidity
- name: setStorageInt3
  call:
    destination: $deployStorageK
    function: setIntToZero
    data: 

- name: queryStorageInt3
  query-contract:
    destination: $deployStorageK
    function: getInt

- name: assertStorageInt3
  assert:
    key: $queryStorageInt3
    relation: ne
    val: 0

#set Int to another number
- name: setStorageBaseInt4
  set:
    val: 777

- name: setStorageInt4
  call:
    destination: $deployStorageK
    function: setInt
    data: [$setStorageBaseInt4]

- name: queryStorageInt4
  query-contract:
    destination: $deployStorageK
    function: getInt

- name: assertStorageInt4
  assert:
    key: $queryStorageInt4
    relation: eq
    val: $setStorageBaseInt4

#set Uint to 9999
- name: setStorageBaseUint
  set:
    val: 9999

- name: setStorageUint
  call:
    destination: $deployStorageK
    function: setUint
    data: [$setStorageBaseUint]

- name: queryStorageUint
  query-contract:
    destination: $deployStorageK
    function: getUint

- name: assertStorageUint
  assert:
    key: $queryStorageUint
    relation: eq
    val: $setStorageBaseUint

#set Uint to 0 using Yaml
- name: setStorageBaseUint2
  set:
    val: 0

- name: setStorageUint2
  call:
    destination: $deployStorageK
    function: setUint
    data: [$setStorageBaseUint2]

- name: queryStorageUint2
  query-contract:
    destination: $deployStorageK
    function: getUint

- name: assertStorageUint2
  assert:
    key: $queryStorageUint2
    relation: ne
    val: $setStorageBaseUint2

#set Uint to 0 using solidity
- name: setStorageUint3
  call:
    destination: $deployStorageK
    function: setUintToZero
    data: 

- name: queryStorageUint3
  query-contract:
    destination: $deployStorageK
    function: getUint

- name: assertStorageUint3
  assert:
    key: $queryStorageUint3
    relation: ne
    val: 0

#set Uint to another number
- name: setStorageBaseUint4
  set:
    val: 111

- name: setStorageUint4
  call:
    destination: $deployStorageK
    function: setUint
    data: [$setStorageBaseUint4]

- name: queryStorageUint4
  query-contract:
    destination: $deployStorageK
    function: getUint

- name: assertStorageUint4
  assert:
    key: $queryStorageUint4
    relation: eq
    val: $setStorageBaseUint4

```
I would expect assertStorageInt2, assertStorageInt3, assertStorageUint2 and assertStorageUint3 to FAIL but they pass, indicating that every time I attempted to reset an int/uint to zero it did not work. 

I am not having this issue on remix. Also I have tried a version of the yaml file with a wait attached to every call, but that did not work either.

Regards,
