### ISSUE TITLE
[question] Burrow server gets blocked when using more than 1 validator

### ISSUE THREAD

**Issue by miguelmartinezinf** [hyperledger/burrow#853]
Please include in your bug report:

- [ ] `monax version` (if applicable)
- [ ] `go version` 1.10.3
- [ ] `burrow version` (docker image tag or branch if built from source)
- [ ] `OS` ubuntu 16.04

## Expected Behavior
The burrow server should run and start adding blocks to the blockchain, increasing the height number.

## Actual Behavior 
When I try to start burrow server using this command `burrow start -v 0` the log shows how the server gets blocked, showing the following error (full log on `burrow.log`):

> {"caller":"reactor.go:253","component":"Tendermint","inbound":0,"log_channel":"Trace","message":"Consensus ticker","module":"blockchain","numPending":1000,"outbound":0,"run_id":"c3e0997a-9ef6-11e8-83c2-62c3cbe0a8a3","scope":"tendermint.NewNode","time":"2018-08-13T12:45:44.061684388Z","total":1000}
> {"caller":"pool.go:167","component":"Tendermint","log_channel":"Trace","message":"Blockpool has no peers","module":"blockchain","run_id":"c3e0997a-9ef6-11e8-83c2-62c3cbe0a8a3","scope":"tendermint.NewNode","time":"2018-08-13T12:45:44.062149982Z"}
> {"caller":"reactor.go:253","component":"Tendermint","inbound":0,"log_channel":"Trace","message":"Consensus ticker","module":"blockchain","numPending":1000,"outbound":0,"run_id":"c3e0997a-9ef6-11e8-83c2-62c3cbe0a8a3","scope":"tendermint.NewNode","time":"2018-08-13T12:45:45.061588604Z","total":1000}
> {"caller":"pool.go:167","component":"Tendermint","log_channel":"Trace","message":"Blockpool has no peers","module":"blockchain","run_id":"c3e0997a-9ef6-11e8-83c2-62c3cbe0a8a3","scope":"tendermint.NewNode","time":"2018-08-13T12:45:45.061963911Z"}

## Steps to Reproduce the Problem

  1. `burrow spec -f 1 -v 1 -p 1 >genesis-spec.json`
  2. `burrow configure -s genesis-spec.json >burrow.toml`
  3. `burrow start -v 0`

## Files

`burrow.toml` [https://pastebin.com/i25mSSFp](https://pastebin.com/i25mSSFp)
`genesis-spec.json` [https://pastebin.com/EEddmLZu](https://pastebin.com/EEddmLZu)
`burrow.log` [https://pastebin.com/MBaXGmD8](https://pastebin.com/MBaXGmD8)

Thanks in advance

**Comment by compleatang** [comment]
In the above setup can you confirm you're starting two nodes and that they're properly connected to one another? Your `burrow.toml` doesn't have a Seeds or PersistentPeers field filled in. With two validator nodes that have equal bonded tokens, you'll need both online and connected in order for the chain to have quorum and move forward. 

If you're just testing locally we highly recommend just using one `full` account rather than a `full` and a `validator` however when you move to early POC / testnet stages then having multiple `validators` can be helpful. In such an instance you'll want to fill in the URLs of the peer ports for those nodes in the PersistentPeers and Seeds fields in the `burrow.toml` so that the nodes can locate one another.

**Comment by miguelmartinezinf** [comment]
Okey, as I can see I should set up two nodes because I have 2 validator accounts.
What does the Seeds field means? What about node address, is that option compulsory for this scenario?
Thanks in advance

**Comment by compleatang** [comment]
high level, you have two nodes and they need to connect to one another in order to have quorum on the network you've defined. in order to do that you'll need to fill in the Seeds or PersistentPeers fields in the burrow.toml for the URL of the "other node". you'll only need to do this for one of the nodes and have it dial the other. once the p2p ports of both nodes are connected to one another then you'll start to create blocks.

the address is the signing key that a particular node will use. that's different from the URL which will be used to dial another node.

**Comment by miguelmartinezinf** [comment]
Hi @phymbert , 
I would like to try it on my own, could you share your configuration files? toml and genesis-spec ?
Thanks in advance

**Comment by phymbert** [comment]
Hello @miguelmartinezinf 

please find below all steps I followed, hope you will reproduce easily.

### Install latest burrow from source

```bash
# be sure to be on latest burrow
mkdir -p $GOPATH/src/hyperledger
cd $GOPATH/src/hyperledger
git clone https://github.com/hyperledger/burrow.git
cd burrow
git checkout develop
go install github.com/hyperledger/burrow/cmd/burrow
(burrow --version | grep 0.22.0) || echo "not latest"
```

### Configure chain
```bash
 rm -rf .burrow* .keys*
 burrow spec -f2 | burrow configure -s- > .burrow_init.toml
```

### Generate one additional key in another local store for seed node
```bash
 burrow spec -f1 | burrow configure --keysdir=.keys_seed -s- > /dev/null
```

### Make 2 validator nodes and one seed node config files
From the generated `.burrow_init.toml `file, create new files for each node, and change the content, example:

#### Seed node `.burrow_seed.toml` modified line from `.burrow_init.toml`
```toml
[Tendermint]
  SeedMode = true
  ListenAddress = "tcp://0.0.0.0:10000"
  Moniker = "seed_node_0"
  TendermintRoot = ".burrow_seed_0"

[Execution]

[Keys]
  GRPCServiceEnabled = false
  AllowBadFilePermissions = true
  RemoteAddress = ""
  KeysDirectory = ".keys_seed"

[RPC]
  [RPC.Info]
    Enabled = true
    ListenAddress = "tcp://127.0.0.1:10001"
  [RPC.Profiler]
    Enabled = false
  [RPC.GRPC]
    Enabled = false
  [RPC.Metrics]
    Enabled = false
```

#### Validator 1 node `.burrow_val0.toml` modified line from `.burrow_init.toml`

```toml
[Tendermint]
  Seeds = "PUT_HERE_SEED_NODE_ID@LISTEN_EXTERNAL_ADDRESS"
  SeedMode = false
  PersistentPeers = ""
  ListenAddress = "tcp://0.0.0.0:20000"
  Moniker = "val_node_0"
  TendermintRoot = ".burrow_node0"

[Execution]

[Keys]
  GRPCServiceEnabled = false
  AllowBadFilePermissions = true
  RemoteAddress = ""
  KeysDirectory = ".keys"

[RPC]
  [RPC.Info]
    Enabled = true
    ListenAddress = "tcp://127.0.0.1:20001"
  [RPC.Profiler]
    Enabled = false
  [RPC.GRPC]
    Enabled = true
    ListenAddress = "127.0.0.1:20002"
  [RPC.Metrics]
    Enabled = false
```

#### Validator 2 node `.burrow_val1.toml` modified line from `.burrow_init.toml`

```toml
[Tendermint]
  Seeds = "PUT_HERE_SEED_NODE_ID@LISTEN_EXTERNAL_ADDRESS"
  SeedMode = false
  PersistentPeers = ""
  ListenAddress = "tcp://0.0.0.0:30000"
  Moniker = "val_node_1"
  TendermintRoot = ".burrow_node1"

[Execution]

[Keys]
  GRPCServiceEnabled = false
  AllowBadFilePermissions = true
  RemoteAddress = ""
  KeysDirectory = ".keys"

[RPC]
  [RPC.Info]
    Enabled = true
    ListenAddress = "tcp://127.0.0.1:30001"
  [RPC.Profiler]
    Enabled = false
  [RPC.GRPC]
    Enabled = true
    ListenAddress = "127.0.0.1:30002"
  [RPC.Metrics]
    Enabled = false
```

#### Start the seed node
```bash
burrow start --validator-address=`basename .keys_seed/data/* .json` --config=.burrow_seed.toml
```

#### Find seed node external address
Tendermint requires strict and routable address (not loopback, local etc), you can find the listen address with this command:
```bash
SEED_URL=`curl -s 127.0.0.1:10001/network | jq -r '.result.ThisNode | [.ID, .ListenAddress] | join("@") | ascii_downcase'`
sed -i s%PUT_HERE_SEED_NODE_ID@LISTEN_EXTERNAL_ADDRESS%${SEED_URL}% .burrow_val0.toml
sed -i s%PUT_HERE_SEED_NODE_ID@LISTEN_EXTERNAL_ADDRESS%${SEED_URL}% .burrow_val1.toml
```

#### Start validator nodes
```bash
burrow start --validator-index=0 --config=.burrow_val0.toml
burrow start --validator-index=1 --config=.burrow_val1.toml
```

#### Disable Tendermint strict address if required
If you face _Cannot add non-routable address_ message in logs, it means your listen address is not routable for tendermint.
You can disable this check by modified default tendermint/config.go:46
```go
conf.P2P.AddrBookStrict = false
```

### Send transactions

#### Create a deploy file _test.yaml_
```yaml
jobs:
- name: sendTxTest1
  send:
      destination: PUT_HERE_ONE_ACCOUNT_OF_YOUR_GENESIS
      amount: 42
```

#### Send it from a node
```bash
SIGNING_ADDRESS=HERE_ONE_ADDRESS_OF_THE_GENESIS
burrow deploy --address $SIGNING_ADDRESS -f test.yaml -u 127.0.0.1:20002
```
It outputs:
```
*****Executing Job*****

Job Name                                    => defaultAddr


*****Executing Job*****

Job Name                                    => sendTxTest1


Transaction Hash                            => 41E0C13D1515F83E6FFDC5032C60682BE1F5B19A
Writing [test.output.json] to current directory
```

### Do it with persistent peers
if you face issue with seed node mode sync (as me), you can easily connect 2 validator nodes directly by setting persistent peers.

```toml
[Tendermint]
  Seeds = ""
  SeedMode = false
  PersistentPeers = "PUT_HERE_NODE_0_ID@LISTEN_EXTERNAL_ADDRESS"
  ListenAddress = "tcp://0.0.0.0:30000"
  Moniker = "val_node_1"
  TendermintRoot = ".burrow_node1"
```

```bash
NODE_0_URL=`curl -s 127.0.0.1:20001/network | jq -r '.result.ThisNode | [.ID, .ListenAddress] | join("@") | ascii_downcase'`
sed -i s%PUT_HERE_NODE_0_ID@LISTEN_EXTERNAL_ADDRESS%${NODE_0_URL}% .burrow_val1.toml
```

Enjoy burrow  🥇
