### ISSUE TITLE
[consensus] Expose Tendermint config CreateEmptyBlocks and CreateEmptyBlocksInterval

### ISSUE THREAD

**Issue by phymbert** [hyperledger/burrow#923]
It should be possible to disable empty block and/or set empty block creation interval by burrow config:

```toml
[Tendermint]
  CreateEmptyBlocks = false
```
