### ISSUE TITLE
[Deploy] Replace ad-hoc templating in deploy.yaml with Go text/template

### ISSUE THREAD

**Issue by silasdavis** [hyperledger/burrow#954]
Currently we have a rather ad-hoc tangle of code that allows us to substitute variables from previous jobs in a deploy.yaml into later jobs. 

The parsing and syntax is provided by some regular expressions mixed with string splitting and other logic that is very far from declarative. Also the structure of the variables you can access is untyped and depends on the job you are referencing, for example:

```yaml
# could be an address from a deploy job
- name: queryStorage
  query-contract:
      destination: $deployStorageK
      function: get
# in a query-account we get named fields
- name: queryPerm1
  query-account:
      account: $addr2
      field: permissions.roles
# In a query-vals we can have jq style deep queries with substitution thrown in!
- name: CheckPower
  query-vals:
    field: "Set.${AddValidator.address}.Power"
```
A much better tool for this sort of work would be text/template. This would firstly give us a decent non-fragile syntax that already exists. The way it would work is by lazily evaluating all keys in our parsed yaml structure as if the are text templates and pass a global object representing the state of past (and future) jobs. This would give the same power as what we have now (the ability to dynamically reference variables initialised in earlier jobs) but we can give each job a strongly typed structure to query over which we can use a reference as what is available. Each job can have a struct describing its result rather than `interface{}` as it is now.
